security:
    encoders:
         App\Entity\Users: bcrypt

    providers:
        database_users:
            entity: { class: App\Entity\Users, property: userName }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/

            anonymous: true

            form_login:
                check_path: security_login

                login_path: security_login

                csrf_token_generator: security.csrf.token_manager

                default_target_path: home


            logout:

                path: security_logout

                target: deco


    access_control:
        - { path: '^/admin', roles: ROLE_ADMIN }
        - { path: '^/former', roles: ROLE_ADMIN }
        - { path: '^/user', roles: ROLE_ADMIN }
        - { path: '^/former', roles: ROLE_FORMER }
        - { path: '^/user', roles: ROLE_FORMER }
        - { path: '^/user', roles: ROLE_USER }