<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6cS81Zj\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6cS81Zj/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container6cS81Zj.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\Container6cS81Zj\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \Container6cS81Zj\srcDevDebugProjectContainer(array(
    'container.build_hash' => '6cS81Zj',
    'container.build_id' => 'be8be359',
    'container.build_time' => 1517075865,
));
